STORYBOOK_COUNT=1 MEASURE_BROWSERS=1   yarn test:visual
STORYBOOK_COUNT=1 MEASURE_BROWSERS=5   yarn test:visual
STORYBOOK_COUNT=5 MEASURE_BROWSERS=1   yarn test:visual
STORYBOOK_COUNT=5 MEASURE_BROWSERS=5   yarn test:visual
STORYBOOK_COUNT=25 MEASURE_BROWSERS=5  yarn test:visual
